name: Docker Image CI

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        username: bfdnd
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#    - name: Docker meta
#      id: meta_step
#      uses: docker/metadata-action@v3
#      with:
#        # list of Docker images to use as base name for tags
#        images: |
#          bfdnd/southwest-check-in
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.10.0
      with:
        context: .
        # List of target platforms for build
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        # List of tags
        tags: bfdnd/undetectable-selenoid-chrome:100.0
